spring:
  config:
    import:
      - application-domain.yaml
  profiles:
    group:
      dev:
        - app-api-dev
        - domains-dev
      local:
        - app-api-local
        - domains-local
    active: ${profile}
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
---
spring:
  config:
    activate:
      on-profile: app-api-dev
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
---
spring:
  config:
    activate:
      on-profile: app-api-local
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
