spring:
  config:
    import:
      - application-domain-rds.yaml
  profiles:
    include:
      - domain-rds-dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
makeabook-app-api:
  download-url-prefix: http://localhost:8080/api/ebook