spring:
  config:
    import:
      - application-domain-rds.yaml
  profiles:
    group:
      local:
        - app-api-local
        - domain-rds-local
    active: ${profile}
---
spring:
  config:
    activate:
      on-profile: app-api-local
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false