spring:
  config:
    import:
      - application-secret.yaml
      - application-domain-rds.yaml
  profiles:
    group:
      local:
        - domain-rds-local
    active: local
  batch:
    job:
      names: ${job.name:NONE}
    jdbc:
      initialize-schema: always
  main:
    web-application-type: none