spring:
  config:
    activate:
      on-profile: domain-redis-dev
  redis:
    port: ${ext-config.redis.secret.port}
    host: ${ext-config.redis.secret.host}
---
spring:
  config:
    activate:
      on-profile: domain-redis-local
  redis:
    port: 6370
    host: localhost
