spring:
  config:
    import:
      - application-domain.yaml
  profiles:
    group:
      prod:
        - app-api-prod
        - domains-prod
      dev:
        - app-api-dev
        - domains-dev
      local:
        - app-api-local
        - domains-local
    active: ${profile}
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
---
spring:
  config:
    activate:
      on-profile: app-api-prod
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
jwt:
  secret:
    key: ${prod-config.jwt.secret.key}
  issuer: ${prod-config.jwt.issuer}
  valid-milliseconds:
    access: ${prod-config.jwt.valid-milliseconds.access}
    refresh: ${prod-config.jwt.valid-milliseconds.refresh}
---
spring:
  config:
    activate:
      on-profile: app-api-dev
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
jwt:
  secret:
    key: ${dev-config.jwt.secret.key}
  issuer: ${dev-config.jwt.issuer}
  valid-milliseconds:
    access: ${dev-config.jwt.valid-milliseconds.access}
    refresh: ${dev-config.jwt.valid-milliseconds.refresh}
---
spring:
  config:
    activate:
      on-profile: app-api-local
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
jwt:
  secret:
    key: It-is-strongly-recommended-that-you-use-a-string-that-is-at-least-512-bits-(64-characters)-long-for-the-secret-key
  issuer: nesonnechek
  valid-milliseconds:
    access: 300000
    refresh: 600000
