spring:
  config:
    import:
      - application-domain-rds.yaml
      - application-domain-redis.yaml
  profiles:
    group:
      domains-local:
        - domain-local
        - domain-rds-local
        - domain-redis-local
---
spring:
  config:
    activate:
      on-profile: domain-local
jwt:
  secret:
    key: ${secret.jwt.key}
    valid-milliseconds:
      access: ${secret.jwt.valid-milliseconds.access}
      refresh: ${secret.jwt.valid-milliseconds.refresh}
