spring:
  config:
    import:
      - application-domain-rds.yaml
      - application-domain-redis.yaml
  profiles:
    group:
      domains-dev:
        - domain-rds-dev
        - domain-redis-dev
        - domain-rds-debug
      domains-local:
        - domain-local
        - domain-rds-local
        - domain-redis-local
        - domain-rds-debug
