spring:
  config:
    activate:
      on-profile: domain-rds-local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${secret.database.url}?serverTimezone=${database.config.time-zone}&characterEncoding=${database.config.encoding}
    username: ${secret.database.username}
    password: ${secret.database.password}
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
database:
  config:
    time-zone: UTC
    encoding: UTF-8
