spring:
  config:
    activate:
      on-profile: domain-rds-local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${secret.database.url}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${secret.database.username}
    password: ${secret.database.password}
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true