name: Test action

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTIONS_TOKEN_2023 }}
      - name: Tset start
        run: echo Start test!
      - name: Echo $GITHUB_ENV
        run : echo $GITHUB_ENV
